# ZSH Role

- name: Install ZSH
  apt: pkg=zsh state=present
  become: yes

- name: Get starship install script.
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: Run starship install script.
  become: yes
  shell:
    cmd: /tmp/starship_install.sh --yes

- name: Create starship.toml
  template:
    src: starship.toml.j2
    dest: ~/.config/starship.toml

- name: Create .zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc

- name: Create .zsh-aliases
  template:
    src: zsh-aliases.j2
    dest: ~/.zsh-aliases

- name: Set default shell
  user: name={{ ansible_user_id  }} shell=/usr/bin/zsh
  become: yes
